//#ifdef DEFINE_GLOBALS

//#define DEFINE_BROWSER_GLOBAL(NAME, VALUE) $NAME = Browser.NAME = VALUE

//#else // !DEFINE_GLOBALS

//#define DEFINE_BROWSER_GLOBAL(NAME, VALUE) Browser.NAME = VALUE

//#endif // !DEFINE_GLOBALS
