//#ifdef DEFINE_GLOBALS

//#define DEFINE_BROWSER_GLOBAL(NAME, VALUE) var $NAME = Browser.NAME = VALUE

//#else // !DEFINE_GLOBALS

//#define DEFINE_BROWSER_GLOBAL(NAME, VALUE) Browser.NAME = VALUE

//#endif // !DEFINE_GLOBALS
